### ISSUE TITLE
Background lol

### ISSUE THREAD

**Issue by DTRW919** [furfsky/furfsky.github.io#13]
Not a real issue but the background can't really squish itself to render on windows smaller than itself. Another thing, pls add animated items to other things in the gallery besides bows. For the credits tab it would be nice if all the people's links went to a certain website, rather than various different ones. Lastly as a suggestion, it would be cool if the site rendered each item in the gallery individually as viewers could hover over them to see what the item actually is (although I guess it's a pain in the rear lol)
<img width="1308" alt="Screen Shot 2021-05-15 at 3 32 05 PM" src="https://user-images.githubusercontent.com/65468867/118379869-b5824c00-b592-11eb-9a71-214e403f559f.png">
^ shows the first "issue"

**Comment by DTRW919** [comment]
I could try to do a pull request of all the links later if you need, keyword **try**

**Comment by DTRW919** [comment]
![FSRBasic-Enlarged](https://user-images.githubusercontent.com/65468867/118381229-96d58280-b59d-11eb-8262-74a83325eb9f.png)
On that note, here is a more refined version of the bg I made as the current one gets a bit blurry zoomed in

**Comment by mr-miner1** [comment]
> Another thing, pls add animated items to other things in the gallery besides bows.

adding animated items to the gallery except for bows is a scuffed impossible idea considering the fact that different items have different amount of frames and frametimes where as all bows have 4 frames with the same frame time making to possible for bows but not other items.

**Comment by RayDeeUx** [comment]
> For the credits tab it would be nice if all the people's links went to a certain website

Not happening. Some of us would rather lay low and have no links at all, others (like me) don't necessarily want to gain attention on the Hypixel forums [hence my choice to link my name to my Reddit account where I'm more well-known for, for example].

> Lastly as a suggestion, it would be cool if the site rendered each item in the gallery individually

Much like many other texture pack showcase posts on the forums, items of a common category are grouped together. FurfSky Reborn is no exception, and zooming in on desktop or mobile will easily suffice in terms of having a closer look at certain textures.

Think of the website as a supplement to the pack/pack's Discord server and not as a replacement.

> Not a real issue but the background can't really squish itself to render on windows smaller than itself.

to be fair if we tried fixing this things would go south for mobile visitors

**Comment by DTRW919** [comment]
Alrighty, thanks :D
