### ISSUE TITLE
Please use alt in <img /> tag.

### ISSUE THREAD

**Issue by Owlahk** [furfsky/furfsky.github.io#17]
Not only it's descriptive for accessibility purposes, but also helps a lot with SEO. 
Moreover, you yourself can quickly read what the img used in code:
[https://i.imgur.com/T7623CR.png](https://i.imgur.com/T7623CR.png)

_Plus my IDE keeps yelling at me that the alt tags are missing so I added them all myself and will submit a new pull request with those soon_

So this is mostly for all future img additions. 
_If you feel like the image cannot be described with text or it's just a design addition, you can simply do alt="" and it's enough (and definitely better than without alt at all)_

**Comment by vooxal** [comment]
Alright, thanks for all of the improvements.

**Comment by RayDeeUx** [comment]
Pull request happened, issue closed.
